#!/bin/bash

active_networks=$(iwgetid)

regex=".+ESSID:\"(.+)\".*"
[[ $active_networks =~ $regex ]]

if [[ $active_networks == "" ]]; then
  echo No Active WiFi Network
  exit 1
fi

echo "${BASH_REMATCH[1]}"
