#!/bin/bash

##
# Get Active WiFi Netork Manager Profile Name
##

active_network_list=$(nmcli -t -f name,type con show --active | grep 802-11-wireless)
regex="(.*):.+"
[[ $active_network_list =~ $regex ]]
active_network="${BASH_REMATCH[1]}"

if [[ $active_network == "" ]]; then
  echo No Active WiFi Network
  exit 1
fi

##
# Lookup Profile
##
profile_psk=`sudo grep psk= "/etc/NetworkManager/system-connections/${active_network}"`
regex="^psk=(.*)"
[[ $profile_psk =~ $regex ]]
active_network_password="${BASH_REMATCH[1]}"

echo $active_network_password
